### ISSUE TITLE
How does proxies work?

### ISSUE THREAD

**Issue by alejosv** [petervmeijgaard/vue-2-boilerplate#50]
I'm starting with Vuejs, and after some time reviewing the framework, I wanted to start with a template, this seems excellent for keeping my first project well structured and at the same time understanding the framework.

I have a question with the proxies. I am implementing them, but using your reference code I get the following error with the login:

    Uncaught ReferenceError: payload is not defined

This is my code in src/store/modules/auth/actions.js

    import Vue from 'vue';
    import Proxy from '@/proxies/AuthProxy';
    import store from '@/store';
    import * as types from './mutation-types';
    ...
    export const login = ({ commit }) => {
        new Proxy()
        .login(payload)
        .then((response) => {
            commit(types.LOGIN, response);
            store.dispatch('account/find');
            Vue.router.push({
                name: 'home.index',
            });
        })
        .catch(() => {
            console.log('Request failed...');
        });
    }
    ...

As I understand it, in `src/pages/login/Index.vue` in the login method, the user object is sent to the `auth/login` action, so this object should arrive as a parameter until actions.js / login. 

What is it missing? The query may be is basic, but I do not see how to go about learning this framework.

**Comment by petervmeijgaard** [comment]
Hi @alejosv! Thanks for your question!

It looks like you forgot to pass the login information to the action. Right now, it only receives one parameter, the `commit`-method. You should also send the user object to the action as well. I prefer to name this object the payload, so that's why I'm doing `.login(payload)` instead of `.login(user)`.

A proxy is used to make performing AJAX requests easier. You can create new proxies by creating a new class in the proxies directory and extending the base proxy. When you want to create a resource like `posts` or `users`, you have instantly access to all the CRUD actions for the API 😊

**Comment by alejosv** [comment]
Hi @petervmeijgaard Thanks for your reply.

I see that the login method is defined as follows in `pages/login/Index.vue`

    methods: {
      ....
      login(user) {
        this.$store.dispatch('auth/login', user);
      },
    },

Yes, the user information is sent to the action, I am still confused, why does not the user reach the action?

**Comment by alejosv** [comment]
Resolved ... thanks for yo help
