### ISSUE TITLE
[FEATURE REQUEST] - Include GraphQL Client

### ISSUE THREAD

**Issue by go4cas** [petervmeijgaard/vue-2-boilerplate#55]
Include a GrpahQL client in the boilerplate, including `proxies` and `store`.

**Comment by petervmeijgaard** [comment]
Hi @go4cas! Sorry for the late response. I've been off the grid for a couple of weeks and finally have a stable WiFi connection.
Hmm, Im still not really sold on including GraphQL in a Vue project. There are a couple of projects and examples out there, but to me it feels like it's more of a hack than a solid solution. And including GraphQL in the Vuex store can be a challenge that I don't know how to handle right now. Don't get me wrong, I really like GraphQL and it's a really awesome project instead of using a traditional API. You could create a PR to add the functionality or drop some ideas here to help me out.

**Comment by petervmeijgaard** [comment]
Because of inactivity, I'm closing this issue
