### ISSUE TITLE
npm WARN deprecated (babel)

### ISSUE THREAD

**Issue by Frankkkkk** [petervmeijgaard/vue-2-boilerplate#56]
When launching `npm i`, I have the following warning message:

`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! `

Thanks

**Comment by petervmeijgaard** [comment]
Hi @Frankkkkk!

Thanks for your issue. My apologies for the late response, but I've been off the grid for a couple of weeks and I've finally found a stable WiFi connection.

I think that this issue will be fixed in the next version of the boilerplate where the Vue CLI 3 service is used. Please be a bit more patient until the project comes out of beta and is stable enough.

**Comment by Frankkkkk** [comment]
No problem ! Thanks for the repo anyways ;-)

**Comment by petervmeijgaard** [comment]
Fixed in the latest version of the boilerplate. Removed the build steps completely and the boilerplate now fully depends on Vue CLI 3. If babel is out of date or deprecated, create an issue at the official Vue CLI repository.
