### ISSUE TITLE
Missing import in store actions

### ISSUE THREAD

**Issue by go4cas** [petervmeijgaard/vue-2-boilerplate#57]
Missing `import Proxy from '@/proxies/AccountProxy';` in `/src/store/modules/account/actions.js`.

**Comment by petervmeijgaard** [comment]
Hi @go4cas,

The comments in the `actions.js`-file are only there to demonstrate how to use the proxy. I'm not importing it, because I don't have a connection to a backend setup. So if I use it at the top of the file, I'm obliged to use it, otherwise ESLint will complain that I'm importing an unused variable.
