### ISSUE TITLE
Deprecated Packages

### ISSUE THREAD

**Issue by SuperlativeEntity** [petervmeijgaard/vue-2-boilerplate#75]
Hi There!

When running npm install, herewith some deprecated packages:

core-js@2.6.11
joi@11.4.0
topo@2.0.2
circular-json@0.3.3
socks@1.1.10
json3@3.3.2

found 11 vulnerabilities (1 low, 1 moderate, 8 high, 1 critical)

**Comment by petervmeijgaard** [comment]
Hi @SuperlativeEntity and thanks for posting an issue. It's been a while since I've updated the packages to the latest version. To be honest, I kinda forgot about this project and wasn't aware that a lot of people are still using it (840+ stars, holy moly 😱 )

I'll try to update the project asap to use the latest packages and best-practices that Vue offers.

Give it a bit more love that it deserves ❤️

**Comment by petervmeijgaard** [comment]
This has been fixed in the latest version
